services:
  - type: web
    name: atbriz-sacco
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_EXCHANGE_API_URL
        value: https://v6.exchangerate-api.com/v6
      - key: VITE_EXCHANGE_API_KEY
        value: 4f4eaecf6de27b7d26170525
